### ISSUE TITLE
Plug-in is screwing up tab setting

### ISSUE THREAD

**Issue by bunnycode** [Microsoft/TypeScript-Sublime-Plugin#133] opened 2015-04-09 19:42 UTC
This plugin is not respecting my setting to use tabs instead of spaces. I believe have every possible setting I can find across both Sublime and the TypeScript plugin to force the editor to always use tabs in every situation. Yet after installing this plugin, whenever I create a new file, or even rename an existing one, it reverts that file back to "Indent with spaces".

**Comment by steveluc** [comment] 2015-04-10 01:12
This is a known issue.  We are testing a fix.

**Comment by DanielRosenwasser** [comment] 2015-04-10 06:45
Duplicate of #129.

**Closed** 2015-04-10 15:13 UTC
Labels: Duplicate
