### ISSUE TITLE
Word multiple selection with pressed ctrl don't work 

### ISSUE THREAD

**Issue by BjornMelgaard** [Microsoft/TypeScript-Sublime-Plugin#518] opened 2016-09-13 20:21 UTC
In all document types on pressed ctrl + double click first word select normally, on next dbclick sublime remove all selections, but must select whole word. 
After removing through Package control all works fine.
Linux, Sublime 3 build 3114

**Comment by BjornMelgaard** [comment] 2016-09-13 20:34
https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/514

With old mousemap dbclick without ctrl don't select word as expected, with new - dbclick+ctrl don't select second and subsequent words as expected, delete this mousemap at all

**Comment by richterdennis** [comment] 2016-09-14 10:25
This bug is so annoying, please fix this as soon as possible

**Comment by alexburner** [comment] 2016-09-14 20:17
Confirmed, issue #514 was happening to me and was very confusing.
Also confirmed, pull #515 fixed 514 but added the new bug described here.

**Comment by richterdennis** [comment] 2016-09-15 08:25
Inspired by #514 and #515, my tmp fix is, adding the `alt` key to the modifiers

`Default.sublime-mousemap`:
```
[
    {
        "button": "button1",
        "count": 2,
        "modifiers": ["ctrl", "alt"],
        "command": "typescript_go_to_ref",
        "press_command": "drag_select"
    }
]
```

**Comment by alexburner** [comment] 2016-09-15 18:01
Yesss @richterdennis that worked for me, thanks!

For anyone else hunting, the file is in `path/to/Packages/TypeScript/Default.sublime-mousemap`

**Comment by SystemDisc** [comment] 2016-09-17 21:36
This issue is very irritating. It took me a bit to figure out which package was responsible.

**Comment by donmckenna** [comment] 2016-10-29 07:41
@richterdennis Thank you, works for me as well!

**Comment by Narretz** [comment] 2016-11-04 11:08
@zhengbli Can we get this issue triaged? This is really annoying since it interferes with core Sublime functionality.

**Comment by stylemistake** [comment] 2016-11-30 13:23
Recently found that this package was the source of this behaviour. Extremely annoying.

**Comment by alexburner** [comment] 2016-12-01 18:23
Bump. Just had to re-hunt this down and patch it again. For my future self, run this:
```
$ subl ~/.config/sublime-text-3/Packages/TypeScript/Default.sublime-mousemap
```

**Comment by alexburner** [comment] 2016-12-01 18:31
Adding a PR to make the patch from @richterdennis official

**Comment by alexburner** [comment] 2016-12-07 21:35
PR #567 has been merged and this issue should be fixed, but I don't have any sort of permissions to close.

**Closed** 2016-12-09 15:51 UTC
