### ISSUE TITLE
Incorrect error spans

### ISSUE THREAD

**Issue by billti** [Microsoft/TypeScript-Sublime-Plugin#192] opened 2015-05-12 15:45 UTC
I'm seeing this on Sublime Text 2 on OS X currently with the latest 'master' bits.  It's very easy to get the error spans out of sync or confused.  For example, see the below 1 char error span left in a valid function after any errors were fixed (the return type), or the one below that where there is one error (no property by that name exists) but it's showing up as 3 separate error spans:

![screen shot 2015-05-12 at 8 37 30 am](https://cloud.githubusercontent.com/assets/993909/7591471/e78ff054-f882-11e4-9f44-7a1f3085df44.png)

![screen shot 2015-05-12 at 8 37 51 am](https://cloud.githubusercontent.com/assets/993909/7591492/043dcd84-f883-11e4-8533-a3d3e3b5d0d2.png)

**Comment by billti** [comment] 2015-05-12 15:51
(Note: I just rolled back to the latest tag and see the same behavior, so this isn't a new issue in 'master').

**Comment by zhengbli** [comment] 2015-05-26 20:48
This is caused by the way we do reloading differently on Sublime 2. I have a fix that will send out PR after the #205 is merged.

**Comment by zhengbli** [comment] 2015-05-26 20:57
See commit 784e70c

**Comment by zhengbli** [comment] 2015-05-27 22:35
Fixed in #205.

**Closed by zhengbli** 2015-05-27 22:35 UTC
Labels: Bug, Fix in review
