### ISSUE TITLE
Colorization breaks when do-while and containing while both have less-thans

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript-Sublime-Plugin#313] opened 2015-07-28 19:11 UTC
```ts
while (0 < 1) {
    do {
    } while (0 < 1);
}

function bar() {
	let x = 'hello';
}
```
![image](https://cloud.githubusercontent.com/assets/6685088/8940960/b9624db8-3521-11e5-83d8-b5e2b4775127.png)

![image](https://cloud.githubusercontent.com/assets/6685088/8940972/c15b1702-3521-11e5-9c1f-cf2e77c8b558.png)

**Comment by hoanhtien** [comment] 2015-07-28 19:34
@RyanCavanaugh This is probably a dupe of https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/265 which was fixed in v0.1.6. Can you upgrade your plugin and try again?

**Closed** 2015-07-28 21:01 UTC
Labels: Duplicate
