### ISSUE TITLE
No space between i and < in for loop breaks formatting

### ISSUE THREAD

**Issue by SomeKittens** [Microsoft/TypeScript-Sublime-Plugin#350] opened 2015-09-06 21:47 UTC
No formatting in Sublime:

```typescript
  for(var i = 0; i< totalTerms; i++) {
    let num = arr[i];
    counts[num] = counts[num] ? counts[num]+1 : 1;
  }
```

Formatting (note space between `i` and `<` in the first line):

```typescript
  for(var i = 0; i < totalTerms; i++) {
    let num = arr[i];
    counts[num] = counts[num] ? counts[num]+1 : 1;
  }
```

Sublime Text 2, Typescript plugin version 0.1.7

**Comment by hoanhtien** [comment] 2015-09-08 18:12
Duplicate of https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/285. We haven't found a good solution for this issue.

**Closed by hoanhtien** 2015-09-08 18:12 UTC
