### ISSUE TITLE
[syntax] add es7 '@' decorator color syntax

### ISSUE THREAD

**Issue by orizens** [Microsoft/TypeScript-Sublime-Plugin#476] opened 2016-05-17 15:53 UTC
Currently, a decorator (es7) isn't recoginzed and colored - as in angular2 i.e:  
```
@Component({
  selector: 'my-app'
})
```
**Component** should be colored.  
There are more decorator names such as: Inject, Directive, RouteConfig, etc...

**Comment by mhegazy** [comment] 2016-05-17 18:10
looks like a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/8.

PRs are welcomed, but please submit them against https://github.com/Microsoft/TypeScript-TmLanguage.

**Closed by mhegazy** 2016-05-17 18:10 UTC
