### ISSUE TITLE
semicolon stops working

### ISSUE THREAD

**Issue by jamiecounsell** [Microsoft/TypeScript-Sublime-Plugin#194] opened 2015-05-12 19:14 UTC
When using the plugin, the semicolon stops working with no indication of why and no pattern. Restarting Sublime Text (3083) did not work for me, but toggling `typescript_auto_format` did.

**Comment by zhengbli** [comment] 2015-05-12 22:27
Do you install from package control or cloned the master branch from the repo?

**Comment by aMarCruz** [comment] 2015-05-14 00:00
Same issue here.
Win7 32bits, Typescript 1.5b, Sublime Text 3 build 3083. ts plugin 1.4 installed from package control.

**Comment by zhengbli** [comment] 2015-05-14 00:45
@jamiecounsell @aMarCruz can you paste the log output in your sublime console? Or better, can you do the following:
1. Go to the typescript plugin folder, edit the ``TypeScript.py`` file to make ``logFileLevel = logging.DEBUG``
2. Open sublime to reproduce the problem, then close it.
3. Open the ``TS.log`` file in the plugin folder (using other editors), paste the content here.
It could be due to that the node server hasn't started.

**Comment by aicioara** [comment] 2015-05-19 17:41
@jamiecounsell how do you toggle `typescript_auto_format` ? 
There is also a related issue, which might be more relevant. Having multiple cursors, hitting semicolon, only inserts semicolon on the first cursor. I believe it has to do because semicolon auto formats the enclosing line(s) and it stops propagating the event to the rest of the cursors. However, I don't want auto format of the text anyway, I can type properly, how do I turn it off?

**Comment by jamiecounsell** [comment] 2015-05-19 18:50
@zhengbli I can't replicate the issue right now. If it happens again I will post the log.
@aicioara glad you figured it out. That's how I did it too. Yes, that would be nice. If it happens again, follow @zhengbli and get the log. Better yet, maybe turn on the log all the time anyway! Hopefully we can get some more information to resolve this issue.

**Comment by zhengbli** [comment] 2015-05-19 20:30
It seems that the way we trigger ``typescript_format_on_key`` command is breaking a range of default editing behaviors in sublime editor, like multi-cursor etc, because we interfere the text inserting process within the command. I'm considering move all the triggering to the ``on_modified`` listener, which in the worst case will guarantee the characters be shown.

**Comment by mdausmann** [comment] 2015-05-21 22:22
+1 this is infuriating! also thanks @aicioara the setting change works.  BTW, are semicolons considered 'bad' syntax for typescript, or this is just a bug?

**Comment by zhengbli** [comment] 2015-05-21 23:16
@mdausmann no it is caused by the way we trigger auto format. The current implementation intercepts the ';' when the user types it, therefore if something goes wrong with the command, the ';' won't show up. We'll change the behavior soon to fix this. And semicolons are **encouraged** in typescript, so don't take it wrong. Thanks for the feedback

**Comment by zhengbli** [comment] 2015-05-27 02:30
I have a fix that will be sent PR after #205 merged, which will be very soon.

**Comment by zhengbli** [comment] 2015-06-08 06:38
@mdausmann @jamiecounsell @aicioara @aMarCruz this should be fixed in master now. Can you guys give it a try?

**Closed** 2015-06-12 00:30 UTC
Labels: Bug, Fixed
