### ISSUE TITLE
Comments not correctly colorized

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-Sublime-Plugin#284] opened 2015-07-09 01:14 UTC
Seen in TypeScript's `src/services.ts` file:

![image](https://cloud.githubusercontent.com/assets/972891/8585889/0d394250-259d-11e5-9636-258831fe2540.png)

**Comment by hoanhtien** [comment] 2015-07-09 23:54
No longer see this issue after upgrading the plug-in. I think this is a dupe of https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/265.

**Closed** 2015-10-20 05:49 UTC
