### ISSUE TITLE
This plugin must be consuming enormous ressources

### ISSUE THREAD

**Issue by dmitriz** [Microsoft/TypeScript-Sublime-Plugin#423] opened 2015-12-28 10:52 UTC
Just installed it via Package Control.
Told me my `typescript` didn't match.
Run `npm update` and sure enough the version is ok.

Suddenly my computer started overheating with dozen processes running from Sublime.

Never ever had this before with any other package!

**Comment by DanielRosenwasser** [comment] 2015-12-28 17:57
Hey @dmitriz sorry to hear about that experience, about how big is your TypeScript project? Would you be able to share your code so we can diagnose the issue at all?

**Comment by dmitriz** [comment] 2015-12-29 05:30
I only wanted to look at some very basic TS files.
Deleted them afterwards to avoid any further problems.
Not using TS myself, just wanted to check it out, now have to stay away :(

**Comment by DanielRosenwasser** [comment] 2015-12-29 05:42
Don't stay away! I'd like to understand what went wrong, and I'd find it really helpful if you'd be willing to tell me more.

You just had a few random `.ts` files and you were seeing high memory usage and multiple processes, right? That's abnormal, so how high are we talking, and what processes were you seeing?

**Comment by dmitriz** [comment] 2015-12-29 06:32
There were multiple processes in my Activity Monitor, Mac OSX 10.8, all called "Sublime" with very high consumption percentage - like 10 of them with above 50% each!

**Comment by dmitriz** [comment] 2015-12-29 07:39
Are Sublime plugins running through all my open files and all open projects without me viewing them?

**Comment by DanielRosenwasser** [comment] 2015-12-29 17:43
My understanding is that the plugin should only spawn an additional Node.js process. Resolving your module dependencies may occur, but that shouldn't spawn any processes.

@zhengbli do you have any clue what might be going wrong?

**Comment by zhengbli** [comment] 2015-12-29 18:19
We have seen a similar issue at #167 that was actually caused by the sublime package control plugin instead of the TypeScript plugin. @dmitriz if you disable the plugin and open the same folder again, would you still see the same resource consumption? Thanks

**Comment by DanielRosenwasser** [comment] 2015-12-29 18:32
@zhengbli, to clarify, do you want @dmitriz to disable the Package Control plugin, or the TypeScript plugin?

**Comment by zhengbli** [comment] 2015-12-29 18:34
Sorry this was not clear enough. I meant for @dmitriz to disable the TypeScript plugin and try again, as this issue might come with the sublime package control plugin instead of ours.

**Comment by dmitriz** [comment] 2016-01-01 11:43
So I ran the re-install but without having any .ts files, it still several heavy processes but eventually stopped. Then I've checked some .ts files and again - a number of massive heavy processes ran and eventually were gone. Not ideals but I can live with that.

**Comment by DanielRosenwasser** [comment] 2016-01-02 02:31
But did disabling the TypeScript plugin temporarily resolve the issue?

**Comment by dmitriz** [comment] 2016-01-02 12:56
I didn't disable. Removed and reinstalled. So far so good. :)

**Comment by subhaze** [comment] 2016-02-05 17:36
Kind of late to the party, but, FWIW, ST could have been reindexing your project for new symbols which can consume a LOT of resources when it does it. Reindexing can be triggered by adding new syntax files and those files matching file types in your project.

This may not have been the issue but something I've ran into before.

**Comment by caJaeger** [comment] 2016-02-09 11:36
I had this same issue, however today I updated sublime, added node_modules to my ignore preferences,  and everything is running perfectly.

**Comment by billti** [comment] 2016-02-09 16:07
@caJaeger can you expand on what you mean? Which "ignore preferences", and which "node_modules" folder (i.e. the one for your project?)

**Comment by caJaeger** [comment] 2016-02-09 17:29
@billti I basically added my project node_modules folder to my sublime preferences as folder it should exclude:
```yaml
"folder_exclude_patterns":
	[
		"node_modules",
		".svn",
		".git",
		".hg",
		"CVS"
	]
```

as well as

**Comment by billti** [comment] 2016-02-09 18:18
Thanks. So per prior comments then, this does appear to be a Sublime indexing issue, and unrelated to the TypeScript plugin. I'll reopen/reinvestigate if any evidence pointing to the TypeScript plugin arises.

**Closed by billti** 2016-02-09 18:18 UTC
Labels: Needs More Info

**Comment by caJaeger** [comment] 2016-02-09 18:22
@billti Yeah, my personal experience certainly points to that being the case.
