### ISSUE TITLE
tsconfig.json settings not taking effect

### ISSUE THREAD

**Issue by musicist288** [Microsoft/TypeScript-Sublime-Plugin#180] opened 2015-05-04 20:19 UTC
Using master on Sublime Text 3 - Ubuntu 14.04.

I have a project with the tsconfig.json file

```JS
{
	"compilerOptions": {
		"module": "commonjs",
		"removeComments": true
	},
	"files": [/* files listed here */]
}
```

but I get the error: `Cannot compile external modules unless the '--module' flag is provided`

I replaced the tsserver directory with same files from typescript 1.5.0-beta and it seems to work just fine.  Are these suppose to be in sync?

**Comment by ddotlic** [comment] 2015-05-04 20:37
Same here, I'm getting weird warnings about accessors only avaible when targeting ES5, which I am (based on my tsconfig.json)

Interestingly, this worked fine until this afternoon. What I did to today is I installed VS 2015RC but made sure that it did **not** put its copy of tsc on a path before node one which I've been using for days without issues.

The other thing I did was update to the latest code and it's entirely possible that this commit borked it: 8e2b009

I'm on Windows 8.1 but apparently this is irrelevant.

**Comment by ddotlic** [comment] 2015-05-04 20:42
I'm seeing significant difference between tsserver as shipped with 1.5 beta and the one in this plugin - is this normal?

Out of curiosity, why not use tsserver as shipped, it's in the path by definition (just next to tsc)?

**Comment by zhengbli** [comment] 2015-05-05 22:05
Sorry a change I made yesterday was intended to incorporate several bug fixes made after 1.5 beta, but I committed a locally built version of tsserver.js instead. Changed them back in #182

**Comment by zhengbli** [comment] 2015-05-05 22:17
The reason why we haven't used the tsserver in the npm package may be we intended to have a different release schedule. However we are definitely considering the option as it would make the experience more consistent.

**Comment by ddotlic** [comment] 2015-05-06 12:37
@zhengbli At this point we the users don't really care this way or another, but the one in the master of this project just plain doesn't work :smiley: , hence this bug report.

**Comment by aminroosta** [comment] 2015-05-06 14:01
any progress on this ?

**Comment by zhengbli** [comment] 2015-05-06 18:34
The changes are in now. @ddotlic  @aminroosta could you give it a shot? Thanks!

**Comment by ddotlic** [comment] 2015-05-06 18:50
Pulled, restarted, no issues. Though it doesn't occur on every restart, so we'll have to wait and see.

**Comment by aminroosta** [comment] 2015-05-06 18:53
@zhanbos  works greak. :)

**Comment by musicist288** [comment] 2015-05-06 18:54
Working here.

**Closed** 2015-05-06 22:21 UTC
Labels: Bug, Fixed
