### ISSUE TITLE
inequality signs break syntax highlight in 0.1.5

### ISSUE THREAD

**Issue by aicioara** [Microsoft/TypeScript-Sublime-Plugin#265] opened 2015-06-29 18:10 UTC
Same bit of code:

- With `<` 
![screen shot 2015-06-29 at 11 06 20 am](https://cloud.githubusercontent.com/assets/3248682/8414759/16c914e4-1e4f-11e5-80ce-ae57e1a7dcd9.png)

- With `==` 
![screen shot 2015-06-29 at 11 06 27 am](https://cloud.githubusercontent.com/assets/3248682/8414762/1c4bf4d6-1e4f-11e5-989b-bad6053a507d.png)

Note: It used to work before the update.

Maybe it is a good idea to separate the syntax highlight from the other features of this plugin. I would like to be able to swap the syntax highlight with my own while also keeping the rest of the features of this plugin

**Comment by hoanhtien** [comment] 2015-06-29 18:51
@aicioara Thanks for the info. Looks like a dupe of or related to https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/262.

The syntax highlighting is pretty self-contained. You can always replace TypeScript.tmLanguage file with that of the previous version (0.1.4) or your own syntax definition.

**Comment by aicioara** [comment] 2015-06-29 18:53
Thank you for the fast response.

**Comment by ddotlic** [comment] 2015-07-05 09:33
I can confirm that issue #271 is related, I can see the same effect with `<` sign but if I only have equality or other criteria the colorization fails for the rest of the file.

It's quite weird, but not a deal breaker as it works in 90% other cases.

**Comment by hoanhtien** [comment] 2015-07-06 23:55
@aicioara @ddotlic We just release `v0.1.6` that includes the fix for this bug. Can you give it a try?

**Comment by zhengbli** [comment] 2015-07-07 18:28
Fixed in #267

**Closed** 2015-07-07 18:28 UTC
Labels: Duplicate
