### ISSUE TITLE
Promise.all() is incorrectly unwrapped

### ISSUE THREAD

**Issue by NekR** [Microsoft/TypeScript-Sublime-Plugin#462] opened 2016-04-03 10:52 UTC
![image](https://cloud.githubusercontent.com/assets/1189265/14232050/42ad9b90-f9a3-11e5-931a-0d4353a9859b.png)

No idea why this happens, but `a` should be of time `number[]`, not `Promise<number>[]`.

My config:

```json
{
  "compilerOptions": {
    "module": "es2015",
    "sourceMap": false,
    "target": "es6",
    "noImplicitAny": true,
    "suppressExcessPropertyErrors": false,
    "jsx": "preserve",
    "suppressImplicitAnyIndexErrors": true,
    "rootDir": "./src",
    "outDir": "./extension"
  },
  "exclude": [
    "node_modules"
  ]
}
```

TS 1.8.9

**Comment by mhegazy** [comment] 2016-04-04 19:06
duplicate of https://github.com/Microsoft/TypeScript/issues/7566

**Closed by mhegazy** 2016-04-04 19:06 UTC
