### ISSUE TITLE
Typescript Plugin Freezes Sublime on Import Syntax

### ISSUE THREAD

**Issue by heinbez** [Microsoft/TypeScript-Sublime-Plugin#505] opened 2016-08-18 02:31 UTC
Hi,

**Issue:** When using the import syntax, for e.g. `import { Service } from './service'` Sublime would become unresponsive right after the first '{' curly bracket, maybe five seconds afterwards it will catch-up to what I typed and will then finally crash Sublime Text completely when trying to specify the import path.

**What I tried:** 
- I completely re-installed Sublime Text 3 (with only typescript plugin installed) on my Windows 10 (x64) machine
- Updated node to the latest version
- Created a new project directory

It's slowly driving me insane.

**Comment by zhengbli** [comment] 2016-09-02 22:12
Do you see error logs in your sublime console?
Also, can you try with the nightly version of TypeScript? The instructions are at:
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#sublime-text
You can get many of the fixes quicker this way before the stable release.

**Comment by w1ndy** [comment] 2016-10-06 06:17
Same here while working on a TypeScript [project](https://github.com/w1ndy/mean.ts). Sublime Text becomes unresponsive every a few characters typed or even crashes when I'm typing the import URLs. I think it could be easily reproduced because I've encountered the same problem while going through the tutorial of Angular 2. Checked both Sublime Text's console and ts.log, nothing came up.

I'm using Sublime Text 3126 and an external tsc 2.0.3 on Windows. Here is my ``tsconfig.json``:
```
{
    "compilerOptions": {
        "target": "es2015",
        "module": "commonjs",
        "rootDir": ".",
        "outDir": "dist/",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": true,
        "suppressImplicitAnyIndexErrors": true,
        "pretty": true
    },
    "include": [
        "typings/**/*",
        "node_modules/@angular/**/*",
        "config/**/*",
        "modules/**/*"
    ]
}
```

Is there any way to enable more verbose logging to provide additional information?

**Comment by Mc128k** [comment] 2016-10-14 12:44
Same problem. It happens in others occasions too, the only workaround is to kill the node process.

**Comment by Mc128k** [comment] 2016-10-24 20:05
Might be a duplicate of #332

**Comment by paradox37** [comment] 2016-11-11 09:47
Same here. Its extremely annoying as it happens pretty often.

**Comment by conic79** [comment] 2016-11-21 16:39
The typescript plugin is causing random crashes.

**Comment by w1ndy** [comment] 2016-11-22 05:03
@zhengbli 

Debug logging shows:
```
2016-11-22 13:00:29,560: 11132: DEBUG: on_idle
2016-11-22 13:00:29,560: 11132: DEBUG: Posting command: {"type": "request", "seq": 210, "command": "geterr", "arguments": {"files": ["X:\\zbuffer.js\\src\\services\\loader.service.ts"], "delay": 500}}
2016-11-22 13:00:29,671: 11132: DEBUG: on_modified
2016-11-22 13:00:29,671: 11132: DEBUG: on_modified_with_info
2016-11-22 13:00:29,672: 11132: DEBUG: Posting command: {"type": "request", "seq": 211, "command": "change", "arguments": {"offset": 40, "insertString": "e", "line": 3, "endOffset": 40, "file": "X:\\zbuffer.js\\src\\services\\loader.service.ts", "endLine": 3}}
2016-11-22 13:00:35,573: 10568: DEBUG: Read body of length: 120
2016-11-22 13:00:35,573: 10568: DEBUG: Body sequence#: 187
2016-11-22 13:00:35,587: 11132: DEBUG: Format on key
2016-11-22 13:00:35,587: 11132: DEBUG: post_on_modified
```
Sublime Text is unresponsive between 13:00:29,672 - 13:00:35,573.

**Closed** 2016-12-22 22:10 UTC
Labels: Needs More Info
